-- Choices are shown in the order the source exam prints them.
--
-- The a/b/c/d order was lost the moment the seed ran. choices has no column
-- for it and its primary key is a random uuid, so /api/questions got its
-- options back from json_agg in whatever order the planner produced - which
-- is not stable between requests. The letters the UI stamps on the options
-- therefore moved around between page loads, and a reviewee checking their
-- answers against the printed reviewer saw mismatches that were not real.
--
-- The order still exists in the seed files, which list every question's
-- options exactly as the exam prints them. This file carries that order over
-- as sort_order, one array per question, matched by option text.
--
-- Run AFTER 20.sql: that file restores Traditional #32's wording, and the
-- questions here are matched on their text.
BEGIN;

ALTER TABLE choices ADD COLUMN IF NOT EXISTS sort_order integer;
ALTER TABLE memorization_choices ADD COLUMN IF NOT EXISTS sort_order integer;

CREATE TEMP TABLE choice_order (
    exam_type exam_type NOT NULL,
    qtext text NOT NULL,
    texts text[] NOT NULL
) ON COMMIT DROP;

INSERT INTO choice_order (exam_type, qtext, texts)
VALUES
    ('TRADITIONAL_LIFE',
     'Both endowment and term life policies provide that',
     ARRAY['No cash value is available to the policy owner during the term of the policy',
            'Renewal and conversion privileges are available',
            'A benefit will be paid at the end of the period of coverage if the person is then alive',
            'Insurance protection will be limited to a specified period']),
    ('TRADITIONAL_LIFE',
     'Indicate which of the following is not a function of an application for life insurance policy.',
     ARRAY['To give details pertaining to non-forfeiture options',
            'To furnish information on which the contract of life insurance may be written',
            'To furnish initial information as to insurability',
            'To convey to the company the desire of the applicant to obtain insurance']),
    ('TRADITIONAL_LIFE',
     'A father has his present life insurance payable to his estate and because he has now retired he wants to pass the policy on to his son who will assume the premium payments. Which of the following will he have to appoint his son to achieve his desire and protect the son from Estate Tax Liability?',
     ARRAY['Irrevocable primary beneficiary',
            'Absolute assignee',
            'Irrevocable secondary beneficiary',
            'Revocable primary beneficiary']),
    ('TRADITIONAL_LIFE',
     'A policy where an irrevocable beneficiary has been designated the insured, without the beneficiary''s permission, can',
     ARRAY['Avail of a non-forfeiture option',
            'Discontinue premium payments',
            'Borrow minimal cash loan',
            'Alter the dividend option now in effect']),
    ('TRADITIONAL_LIFE',
     'What are the basic settlement options?',
     ARRAY['Policy loan, guaranteed insurability',
            'Cash surrender value, automatic premium loan',
            'Fixed amount, fixed period, life income, interest on deposit',
            'Double indemnity, total and permanent disability waiver']),
    ('TRADITIONAL_LIFE',
     'An insurance company generally has the right to rescind a life insurance policy if',
     ARRAY['Company discovers at any time that the policy owner was actually a minor at the time of application',
            'Insured person intentionally kills himself during the suicide exclusion period specified in the policy',
            'Insured person is killed in military action during the contestable period of the policy',
            'Company discovers during the contestable period that the application contains a material statement']),
    ('TRADITIONAL_LIFE',
     'Which of the following is the least important reason for requiring that insurance agents be licensed?',
     ARRAY['To establish and maintain high professional and ethical standards',
            'To protect the public',
            'To give the government adequate control over the conduct of agents',
            'To provide additional income to the government through license fees']),
    ('TRADITIONAL_LIFE',
     'In the event that a policy owner elects the paid-up insurance option',
     ARRAY['The premiums stop and the policy continues for the full face amount until age 65',
            'The insurance continues at a reduced amount and with a reduced premium',
            'The policy will automatically terminate',
            'The premiums cease and protection continues with a reduced amount of coverage']),
    ('TRADITIONAL_LIFE',
     'The company will allow a policy change from a higher premium to a lower premium provided the insured',
     ARRAY['Buys a new plan altogether',
            'Presents satisfactory evidence of insurability',
            'Momentarily assigns the policy to the company',
            'Obtains written consent from his or her spouse']),
    ('TRADITIONAL_LIFE',
     'A policy which permits the policyholder to vary the level of premiums, the sum insured and has its cash values dependent upon the investment performance and the level of premium paid is known as policy',
     ARRAY['Participating whole life policy',
            'Participating endowment',
            'Universal life',
            'None of the above']),
    ('TRADITIONAL_LIFE',
     'Which of the following statements about "Disability Waiver of Premium Rider" is false?',
     ARRAY['Disability must occur before a stated date',
            'The insured has to die while disabled',
            'There is a waiting period',
            'It has to be attached to a life insurance policy']),
    ('TRADITIONAL_LIFE',
     'In most life insurance applications, the largest amount of information requested is data which',
     ARRAY['Identifies the applicant',
            'Describes the type of insurance applied for',
            'Relates to the insurability of the applicant',
            'Describes the desired benefits and mode of payment']),
    ('TRADITIONAL_LIFE',
     'Paid-up additions',
     ARRAY['Affect both cash and loan value of the policy',
            'Don''t affect the cash value of the policy',
            'Don''t affect the loan or cash value of the policy',
            'Only affect the cash value of the policy']),
    ('TRADITIONAL_LIFE',
     'The total life coverage of a permanent basic policy can be greatly increased through the use of',
     ARRAY['An accidental death benefit rider',
            'An interim term rider',
            'A supplemental term rider',
            'None of the above']),
    ('TRADITIONAL_LIFE',
     'Life insurance companies make use of the laws of probability in order to',
     ARRAY['Estimate future death rates among members of a given group',
            'Predict when an individual insured will die',
            'Develop statistics of past deaths among the general population',
            'Determine the experienced death rate among the insured persons']),
    ('TRADITIONAL_LIFE',
     'In the case of renewable term insurance, the policy owner may',
     ARRAY['Renew the coverage based on a higher premium',
            'Change the life insured at renewal date',
            'Renew providing the insurance company agrees to continue coverage',
            'Renew at the same premium for further period of years']),
    ('TRADITIONAL_LIFE',
     'A man applied for a Ps. 20,000 whole life policy and paid the full initial premium to the soliciting agent. The agent issued a binding receipt. Under such a receipt, the insurance company',
     ARRAY['Offers permanent insurance coverage effective as of the date of the application',
            'Promises that the insurance coverage will become effective as of the date the application is approved',
            'Guarantees the policy will be issued as applied for',
            'Immediately provides interim insurance that remains in effect until the policy is issued or the application is declined']),
    ('TRADITIONAL_LIFE',
     'Endowment life insurance and term life insurance are similar in that both plans',
     ARRAY['Build up cash value rapidly in the early policy years',
            'Provide for payment of the face amount if the insured is alive at the end of the specified period',
            'Provide life insurance protection for only the period of time specified in the policy contract',
            'Contain provisions for automatic continuation of the insurance protection at the end of a specified period']),
    ('TRADITIONAL_LIFE',
     'An agent who determines a prospect''s complete financial requirements preparatory to offering him a policy using the correct selling approach knows as',
     ARRAY['Counselor selling',
            'Total needs selling',
            'Planned selling',
            'Multiple products selling']),
    ('TRADITIONAL_LIFE',
     'Name the provision in a permanent life insurance policy under which premiums are discontinued, full insurance will be maintained for a specified period:',
     ARRAY['Extended term insurance',
            'Paid-up insurance additions',
            'Life income option pension',
            'Reduced paid-up insurance']),
    ('TRADITIONAL_LIFE',
     'Notwithstanding various possible legal impediments, if the owner of an endowment at age 65 policy tells you that the maturity of the policy he wants to provide his church with a monthly donation for as long as the church exists, which option do you recommend?',
     ARRAY['Fixed income option',
            'Periodic annuity option',
            'Interest option',
            'Life annuity option']),
    ('TRADITIONAL_LIFE',
     'The extent of medical evidence required is determined by',
     ARRAY['The age of the applicant and the proposed sum to be insured',
            'Occupation of the applicant',
            'Financial condition of the applicant',
            'Date of the last medical examination']),
    ('TRADITIONAL_LIFE',
     'The conservation of a life insurance policy is dependent on all the following except',
     ARRAY['The level of first year commission',
            'Agent''s service oriented attitude',
            'Pressure selling',
            'The use of effective needs selling']),
    ('TRADITIONAL_LIFE',
     'All of the following are sources of information to an insurance company pertaining to the insurability of an applicant except',
     ARRAY['The applicant''s personal appearance',
            'Medical examination report',
            'Agent''s inspection report',
            'Government tax records']),
    ('TRADITIONAL_LIFE',
     'If the applicant for life insurance fails to disclose or misrepresents material fact, the contract is',
     ARRAY['Valid if the insurer issues a policy which is delivered to the applicant',
            'Void from the beginning',
            'Voidable by the insurer if it has been in force less than 2 years',
            'Valid unless the insurer can prove fraud']),
    ('TRADITIONAL_LIFE',
     'The settlement options provision may provide all of the following except:',
     ARRAY['Payment of the proceeds for the life of the insured',
            'Payment of the proceeds over a fixed period',
            'Payments of the proceeds in fixed amounts until exhausted',
            'Proceeds held by the company, with interest payable to the beneficiary on request']),
    ('TRADITIONAL_LIFE',
     'Non-forfeiture provisions are included in whole life and endowment policies to assure the policyowner that certain minimum policy benefits shall remain with him even under certain changed conditions. Non-forfeiture values guarantee to the policyowner that',
     ARRAY['No death claim will be denied for any misstatement on the application',
            'Any guaranteed policy values will belong to the policy owner even if premium payments are discounted',
            'The face amount of the policy will remain the same even if the insured''s health becomes impaired',
            'The premium on the policy will remain the same even when another beneficiary is added to the policy']),
    ('TRADITIONAL_LIFE',
     'Purchasing a continuous-premium, whole life policy rather than a limited payment, whole life policy gives the policyowner the advantage of',
     ARRAY['Concentration of premium payments during the period of highest earnings',
            'Liberal risk selection procedures',
            'More insurance protection for the same annual premiums outlay',
            'More rapid accumulation of cash values']),
    ('TRADITIONAL_LIFE',
     'In certain situations a company may file interpleader actions with a Court of Law. This remedy is used to',
     ARRAY['Determine if the cause of the insured''s death was an excluded risk',
            'Decide conflicting claims on the same insurance proceeds',
            'Resolve the question of insurable interest',
            'Recommend the best settlement options for the beneficiary']),
    ('TRADITIONAL_LIFE',
     'Which of the following statement is false?',
     ARRAY['The cash value of a whole life policy builds up at a slower rate than for a 20 year endowment',
            'The cash value in a permanent policy is guaranteed by the company',
            'The cash value of an endowment builds up faster than that for a limited pay life policy of the same duration',
            'Because of its very short duration the cash value of a yearly renewable term policy grows very fast']),
    ('TRADITIONAL_LIFE',
     'Which of the following does not have a legitimate insurable interest?',
     ARRAY['An individual on the life of his mistress',
            'An individual on his own life',
            'An individual on the life of his spouse',
            'A finance company on the life of its borrower']),
    ('TRADITIONAL_LIFE',
     'The basic coverage provided by the life insurance policies may be supplemented by a separate provision that provides coverage for accidental amounts or of a different nature. Collectively these provisions are known as',
     ARRAY['Riders',
            'Deposit privileges',
            'Dividends',
            'Assignment']),
    ('TRADITIONAL_LIFE',
     'Which of the following statements regarding insurance premiums is false?',
     ARRAY['Cash is required for all premiums paid in the grace period',
            'A premium is the legal consideration needed to affectuate a life insurance policy',
            'The grace period is usually 31 days',
            'Premiums which are paid quarterly or semi-annually are higher than those paid annually']),
    ('TRADITIONAL_LIFE',
     'A non-forfeiture option would ordinarily be selected at the time a policyowner',
     ARRAY['Renews a term life policy',
            'Converts a term policy to a whole life policy',
            'Chooses a mode of settlement for the life proceeds',
            'Discontinues premium payments for a whole life or endowment policy']),
    ('TRADITIONAL_LIFE',
     'If the interest on a policy loan is not paid at the policy anniversary the insurance company may',
     ARRAY['Demand full settlement of the loan',
            'Terminate the contract',
            'Refuse to grant future additional loan',
            'Increase the present loan by the interest']),
    ('TRADITIONAL_LIFE',
     'The incontestability clause',
     ARRAY['Gives the company the right to rescind a policy at any time',
            'Permits the company to pay claims within 2 years',
            'Makes it necessary for the beneficiary to present proof of death in the event of a death claim',
            'Prevents the company from denying a claim after the policy has been in force for 2 years']),
    ('TRADITIONAL_LIFE',
     'The insured named a primary and secondary revocable beneficiary for Ps. 20,000 policy. Which of the following is correct?',
     ARRAY['The designation of a contingent beneficiary is subject to the primary beneficiary''s approval',
            'The insured can add a third beneficiary at any time',
            'Any policy loan assignment will require the primary beneficiary''s signature',
            'Upon the insured''s death the primary and secondary beneficiaries shall each receive Ps. 10,000']),
    ('TRADITIONAL_LIFE',
     'When you bought an insurance policy on your wife''s life, you were 27 and she was 26, but you stated that you were 26 and she was 27. Five years later your wife died. The insurer will pay',
     ARRAY['Slightly less than the face amount',
            'The face amount',
            'The face amount adjusted for misstatement of age',
            'The sum of the premium paid']),
    ('TRADITIONAL_LIFE',
     'A yearly renewable term life insurance policy generally specifies that',
     ARRAY['The policyowner may renew the policy only once',
            'Premiums shall increase every time the policy is renewed',
            'Evidence of insurability shall be required every renewal',
            'Cash values will increase for as long as the policy is in force']),
    ('TRADITIONAL_LIFE',
     'True or False: In a case where the premium has not been paid and the cash values has been exhausted, the policy can still avail of the grace period.',
     ARRAY['True',
            'False']),
    ('TRADITIONAL_LIFE',
     'True or False: According to the law of large numbers, events which happen seemingly by chance will actually be bound to follow a predictable pattern, if enough such happenings are observed.',
     ARRAY['True',
            'False']),
    ('TRADITIONAL_LIFE',
     'True or False: Anti-selection occurs when persons in poor health wish to buy insurance.',
     ARRAY['True',
            'False']),
    ('TRADITIONAL_LIFE',
     'True or False: A policy is still in force for the full face amount and will remain in force for a further period of four years and 118 days, without the payment of any premiums has availed of paid up insurance option.',
     ARRAY['True',
            'False']),
    ('TRADITIONAL_LIFE',
     'True or False: In the case of misstatement of age, the amount of insurance is adjusted to the amount which the premium paid at the correct age would have purchased.',
     ARRAY['True',
            'False']),
    ('TRADITIONAL_LIFE',
     'True or False: A policy that provides guaranteed cash values plus extra annual distributions and pays the insured after a specified time is known as a participating endowment.',
     ARRAY['True',
            'False']),
    ('TRADITIONAL_LIFE',
     'True or False: In a group insurance it is assumed that every member of the group is insurable, provided that every member of the group is working a minimum number of (usually 50 hours) each week.',
     ARRAY['True',
            'False']),
    ('TRADITIONAL_LIFE',
     'True or False: An endowment at age 65 policy with premium payable for a limited period of 20 years pays the full amount after 20 years.',
     ARRAY['True',
            'False']),
    ('TRADITIONAL_LIFE',
     'True or False: In most life insurance applications, the largest amount of information requested is data which identifies the applicant.',
     ARRAY['True',
            'False']),
    ('TRADITIONAL_LIFE',
     'True or False: A policy is not rendered void by reason of misstatement of the assured''s death.',
     ARRAY['True',
            'False']),
    ('VUL',
     'Variable life insurance policy owners may make withdrawals in terms of ___________.',
     ARRAY['Number of units or fixed monetary amount through cancellation of units',
            'Number of units of fixed monetary through reduction of the life cover sum assured',
            'Fixed monetary amount only through reduction of the life cover sum assured',
            'Number of units through cancellation of units']),
    ('VUL',
     'Which of the following statements about flexibility features of variable life policies is false?',
     ARRAY['Policyholders may request for a partial withdrawal of the policy and the withdrawal amount will be met by cashing the units at the bid price.',
            'Policyholders can take loans against their variable life up to the entire withdrawal value of their policies',
            'Policyholders have the flexibility of switching from one fund to another provided it satisfies the company''s switching criteria',
            'Policyholders have the flexibility of increasing or decreasing their premiums for regular premium variable life policies']),
    ('VUL',
     'The investment returns under variable life insurance policy ___________. I. Are not guaranteed II. Are assured III. Are linked to the performance of the investment fund managed by the life insurance company IV. Fluctuate according to the rise and fall of market prices',
     ARRAY['I, II and III',
            'I, II and IV',
            'I, III and IV',
            'II, III and IV']),
    ('VUL',
     'Which of the following statements is TRUE? I. The policy value of variable life policies is determined by the offer price at the time of valuation II. The policy value of endowment policies is the cash value plus any accumulated dividends less any outstanding loans due at the time of the surrender III. The life company needs to maintain a separate account for variable life policies distinct from the general account',
     ARRAY['I & II',
            'I, II & III',
            'I & III',
            'II & III']),
    ('VUL',
     'Which of the following statements is FALSE?',
     ARRAY['Rebating is to offer a prospect a special inducement to purchase a policy',
            'Twisting is a specific form of misrepresentation',
            'Misrepresentation is a specific form of twisting',
            'Switching is a facility allowing the policyholders to switch to another variable life funds offered by the company']),
    ('VUL',
     'Which of the following statements about variable life policies is TRUE? I. Offer price is used to determine the number of units to be credited to the account II. The margin between the bid and offer price is used to cover the managements cost of the policy III. The policy value is calculated based on the bid price of units allocated into the policy',
     ARRAY['I, II & III',
            'I & II',
            'I & III',
            'II & III']),
    ('VUL',
     'What is the most suitable investment instrument for an investor who is interested in protecting his principal and receiving a steady stream of income?',
     ARRAY['Equities',
            'Warrants',
            'Variable life policies',
            'Fixed income securities']),
    ('VUL',
     'What are the disadvantages of investing in common shares? I. Dividends are paid more than fixed rates II. Investors are exposed to market and specific risks III. Shares can become worthless if company becomes insolvent',
     ARRAY['I & II',
            'I & III',
            'II & III',
            'I, II & III']),
    ('VUL',
     'Which of the following statements about the difference between variable life policies and endowment policies are FALSE? I. The policy values of variable life policies directly reflect the performance of the fund of the life company II. The premiums and benefits of the endowment policies are described at the inception of the policy whereas variable life are flexible as the are account driven III. The benefits and risks of variable life and endowment policies directly accrue to the policyholders',
     ARRAY['I & II',
            'I, II & III',
            'I & III',
            'II & III']),
    ('VUL',
     'Which of the following statements about twisting is FALSE?',
     ARRAY['Twisting is a special form of misrepresentation',
            'It refers to an agents including a policyholder to discontinue policy with another company without disclosing the disadvantage of doing so',
            'It includes misleading or incomplete comparison of policies',
            'It refers to an agent offering a prospect a special inducement to purchase a policy']),
    ('VUL',
     'Mr. Juan dela Cruz is currently earning Php 30,000.00 per month. He is 35 years old and he has a reasonable amount of savings. He has a moderate level of risk tolerance. What kind of policy would you recommend for him to buy?',
     ARRAY['Participating Endowment',
            'Variable life policies',
            'Participating whole life',
            'Annuities']),
    ('VUL',
     'What are the benefits available when investing in variable life funds? I. The variable life funds offer policyholders an access to pooled or diversified portfolios II. The variable life policyholders can vary his premium payments, take premium holidays, add single premium top-ups and change the level of the sum assured easily III. The variable life policyholder can have access to a pool of qualified and trained professional fund managers',
     ARRAY['I & II',
            'I & III',
            'I, II & III',
            'II & III']),
    ('VUL',
     'Rank the following in terms of their liquidity, from the least liquid to the most liquid: I. Short term securities II. Property III. Cash IV. Equities',
     ARRAY['IV, II, III, I',
            'III, I, IV, II',
            'II, I, IV, III',
            'II, IV, I, III']),
    ('VUL',
     'A unit trust is ___________.',
     ARRAY['Established by a trust deed which enables a trustee to hold the pool of money and assets in trust in behalf of the investor',
            'A close-end fund and does not have to dispose off if the large number investors sell their shares',
            'One whereby the investor buys units in the trust itself and not share in the company',
            'An organization registered under the SECURITY EXCHANGE COMMISSION (SEC) which usually invests in a wide range of equities and other investment']),
    ('VUL',
     'Under variable life insurance policies ___________. I. There is no guaranteed minimum sum assured for the purpose of declaring dividends II. There is no guaranteed minimum sum assured as a level of life insurance protection III. Each of the policy owner''s premium will be used to purchase units the number of which is dependent on the selling price of each unit IV. Purchase of units can only be made from the variable life fund itself, which will then create new units and add investment monies to the value of the fund',
     ARRAY['I & IV',
            'II & IV',
            'III & IV',
            'II & III']),
    ('VUL',
     'The benefits of investing in variable life funds include ___________. I. Policy owners have access to pooled or diversified portfolios of investment II. Policy owners can easily change the level of the premium payments as the product design of variable life policies have clear structures which cater separately for investment and insurance protection III. Policy owners can gain access to variable life funds managed by professional investment managers with proven track records IV. Policy owners can buy a variable life insurance policy only with a high initial investment',
     ARRAY['I, II & IV',
            'I, III, & IV',
            'I, II & III',
            'II, III & IV']),
    ('VUL',
     'Which of the following BEST describes the policy benefits of variable life policies?',
     ARRAY['The policy benefits are payable only on death or disability',
            'The policy benefits will depend on the long-term performance of the life company.',
            'The policy benefits are directly linked to the investment performance of the underlying assets',
            'The policy benefits are guaranteed']),
    ('VUL',
     'Why is it important that the customer must understand the sales proposal in full?',
     ARRAY['Because the insurer does not guarantee any return',
            'Because the impact of changes in investment condition on variable life policy is borne solely by the customer.',
            'Because the agent may give the wrong recommendations',
            'Because the policyholder expects higher returns']),
    ('VUL',
     'Which of the following statements about rebating are TRUE? I. Rebating is prohibited under the Insurance Code II. Rebating deals with offering the prospect a special inducement to purchase a policy III. Rebating will enhance the sales performance and uphold the prestige of an agent.',
     ARRAY['I & II',
            'I & III',
            'II & III']),
    ('VUL',
     'Which one of the following statements is FALSE?',
     ARRAY['Variable life insurance policies offer investors policies with values and indirectly linked to the investment performance of the life company',
            'Life company will carry out a valuation of its funds yearly and any surplus may be allocated to participating policyholder as cash dividends',
            'Both Whole Life and Endowment policies can be used as an investment media with benefits that become payable at a future date',
            'The investment element of Variable life policies varies according to underlying assets of the portfolio']),
    ('VUL',
     'Which of the following statements about option top-up under variable life insurance is false?',
     ARRAY['Policy owners may buy additional units of the variable life fund and these units will be allocated to new variable life insurance policies',
            'Further premiums at time of the top-up will be used in full, after deducting charges for top-ups, to purchase additional units of the variable life funds',
            'Top-up policy, the policy owner pays further single premium at the time of the top-up',
            'Policy owners are normally allowed to top-up their policies at any time, subject to a minimum amount']),
    ('VUL',
     'The characteristics of a variable life insurance include ___________: I. Its withdrawal value and protection benefits are determined by the investment performance of the underlying assets. II. Its protection costs are generally met by implicit charges III. Its commission and company expenses are met by a variety of explicit charges with normally 6 months notice given by the life companies prior to any change IV. Its withdrawal value is normally the value of units allocated to the policy owner calculated at the bid price',
     ARRAY['I, II & III',
            'II, III & IV',
            'I, II & IV',
            'I, III & IV']),
    ('VUL',
     'Which of the following statements about single premium variable life policies are TRUE? I. There is no fixed term in a single premium variable life policy and therefore, they are technically whole life insurance II. Top-ups or single premium injections are allowed in these plans III. Policyholders have the flexibility of varying the level cover',
     ARRAY['I, II & III',
            'II & III',
            'I & II',
            'I & III']),
    ('VUL',
     'Investing in bonds offer the following EXCEPT',
     ARRAY['Must be issued with a minimum death benefit',
            'Must be issued with a maximum withdrawal value',
            'It allows the investor a chance for capital preservation',
            'It enables the investor an opportunity for capital appreciation']),
    ('VUL',
     'Which of the following statements about variable life policies are TRUE? I. The withdrawal value is not guaranteed II. The volatility of the returns depends on the investment strategy of the fund III. The variable life policyholder has direct control over the investment decisions of the variable life fund',
     ARRAY['I, II & III',
            'I & II',
            'I & III',
            'II & III']),
    ('VUL',
     'Single premium variable life insurance policy:',
     ARRAY['Must be issued with a minimum death benefit',
            'Must be issued with a maximum withdrawal value',
            'Has no death benefit',
            'Has no withdrawal value']),
    ('VUL',
     'Which of the following statements about characteristics of variable life policies are TRUE? I. Variable policies generally have a longer exposure to equity investment than with participating and other traditional policies II. The protection costs are generally met by implicit charges, which vary with age and level of cover III. The commissions and company expenses are met by a variety of explicit charges, some of which are variable',
     ARRAY['I, II & III',
            'I & II',
            'II & III',
            'I & III']),
    ('VUL',
     'Which of the following statements about benefits in variable life fund is FALSE?',
     ARRAY['The fund provides a highly diversified portfolio, thus, lowering the risk of investment',
            'The fund ensures definite high yield for an investor since it is managed by professionals who are well-versed in the management of risk of investment portfolios',
            'The fund relieves the investor from the hassle of administering his / her investment',
            'The fund enables small investors to participate in a pool of diversified portfolio in which he / she, with a low investment capital, is likely to have acceded to']),
    ('VUL',
     'The flexibility benefit of investing in variable life funds include ___________: I. Policy owners can easily change the level of sum assured and switch their investment between funds II. Policy owners can easily take premium holidays and add single premium to Top-ups III. Variable life insurance policies offer the potential for higher returns IV. Traditional participating policies aim to produce a steady return by smoothing out market fluctuation',
     ARRAY['All of the above',
            'I, II & III',
            'I, II & IV',
            'I, III & IV']),
    ('VUL',
     'The fundamental differences between traditional participating life insurance policies and variable life insurance policies include ___________. I. Variable life insurance policies are less likely to offer more choices in terms of the type of investment funds II. The investment elements of variable life insurance policies is made known to the policy owner at the outset and is invested in a separately identifiable fund which is made up of units of investment III. Variable life insurance policies offer the potential for higher returns IV. Traditional participating policies aim to produce a steady return by smoothing out market fluctuation',
     ARRAY['I, III & IV',
            'II, III, IV',
            'I, II, III',
            'I, II & IV']),
    ('VUL',
     'The switching facility under variable life insurance policies is a very useful ___________',
     ARRAY['For the purpose of profit planning by the life policies',
            'For the purpose of assets planning by the trustee',
            'For the purpose of sales planning by the fund managers',
            'For the purpose of financial planning by the policy owners']),
    ('VUL',
     'The following statement about surrender value under traditional participating life insurance products are TRUE?',
     ARRAY['Cash value is paid when yearly renewable term insurance policy is surrendered',
            'When a participating insurance policy is surrendered, the surrender value is calculated by multiplying the bid price with the number of units',
            'The amount of surrender value is usually higher than the amount under non-participating policies and it varies with the age of the assured, being lower at older ages',
            'In the case of participating policies, the net cash surrender value includes the surrender value of the paid-up addition up to the date of surrender']),
    ('VUL',
     'Which one of the following statements about risks of investing in variable life funds is TRUE?',
     ARRAY['Policy owners who are risk averse should buy life insurance policies with high equity investment',
            'Investment in variable life funds which are fully invested in units of equity bonds are not suitable for policy owners who can tolerate the risks of short term fluctuation in their cash value',
            'Policy owners who invest in variable life funds with high equity investment face higher risk but can expect to achieve higher return than the traditional life insurance product over the long term',
            'Policy owners who are risk averse should not purchase life insurance policies with high protection and guaranteed cash and maturity values']),
    ('VUL',
     'What should be the withdrawal values after a year? Offer Price = Php. 16.00; Bid-Offer Spread = 4.5%; Number of units bought = 25,000; Policy Fee = 1,800; Admin and Mortality Charge = 8,750; Top-up Fee = 700; Admin for Top-up = 2000. Sum assured is 190% of single premium or the value of units, whichever is higher.',
     ARRAY['Php. 432,000.00',
            'Php. 420,069.20',
            'Php. 401,107.58',
            'Php. 412,500.00']),
    ('VUL',
     'The protection cost under a variable life insurance policy ___________. I. Are met by flat initial charges for regular premium plans II. Are generally covered by cancellation of units in the fund III. Are generally met by explicit charges stipulated openly in the policy terms IV. Vary with age of policy owner and level of cover',
     ARRAY['I, II, & III',
            'I, II, & IV',
            'I, III & IV',
            'II, III, & IV']),
    ('VUL',
     'Which of the following statements about diversification in portfolio management is FALSE?',
     ARRAY['A diversified portfolio provides greater security to an investor having to sacrifice return for the portfolio.',
            'Diversification can completely eliminate the risk of investing in stocks in a portfolio.',
            'Diversification can involve purchasing different types of stocks and investing stocks in different countries',
            'Diversification helps to spread the portfolio risk by investing in different categories of investment in a portfolio']),
    ('VUL',
     'What are the advantages of investing in preferred shares? I. It gives shareholders the right to a fixed dividend II. Has the priority over company assets during a dissolution III. They enjoy benefit of capital appreciation',
     ARRAY['I, II, & III',
            'I & II',
            'I & III',
            'II & III']),
    ('VUL',
     'With traditional participating life insurance products, the allocations to policy owners in the form of dividends ___________: I. Are not directly linked to the company''s investment performance II. Have already been smoothened by the life company III. Do not have the highs and lows of investment return as in good investments years of life company IV. Are not fixed at the inception of the policy, but are greatly dependent on the investment performance of the company.',
     ARRAY['I, II, & III',
            'I, II & IV',
            'I, III, & IV',
            'II, III, & IV']),
    ('VUL',
     'The objective of satisfying customers need profitably can be achieved by and agent through I. The giving of freebies to the customers II. Extensive investment training by the company III. The use of sales plan, where sales goals, strategies, and objectives are coordinated with the market analysis, segmentation and training IV. The giving of monetary assistance and discount to the customers',
     ARRAY['I & III',
            'II & III',
            'II & IV',
            'II, III, & IV']),
    ('VUL',
     'Which of the statements is true about CASH?',
     ARRAY['It has a high yield potential',
            'Amount invested in cash depends on size of the cash flow requirement',
            'Investment in cash increase when there is a bull run in the stock market',
            'Investment in cash decrease when interest rates rise']),
    ('VUL',
     'Under a regular premium variable whole life plan ___________. I. Premium top-ups and holidays, subject to the company''s administrative rules are usually allowed II. Life protection is the main objective of the plan with investment as the nominal purpose III. Withdrawals after the payment of a few years premium are usually allowed IV. A single premium contribution is made to the policy which uses the premium to purchase units in a variable life fund to provide a certain level of life cover',
     ARRAY['II, III & IV',
            'I, III & IV',
            'I, II, & IV',
            'I, II, & III']),
    ('VUL',
     'Which of the following statements about investment objectives is false?',
     ARRAY['People invest money in fixed deposits to produce high and guaranteed returns',
            'People invest money to enhance a comfortable standard of living',
            'People invest money to provide funds for higher education for their children',
            'Investment in commodities has no regular income']),
    ('VUL',
     'Which of the following is / are the main characteristic(s) of variable life policies? I. The policies can be used for investment, as a source of regular savings and protection II. The withdrawal values and protection benefits are determined by the investment III. The net cash values of the policies are the gross cash values shown in the policy that includes dividends up to the date of surrender less and indebtedness including interest',
     ARRAY['II',
            'I',
            'I, II, & III',
            'I, & II']),
    ('VUL',
     'Risk can be classified into two particular categories in relation to investment. They include ___________: I. The risk of not losing some or all of the person''s initial investment II. The risk of rate of return on the investment not matching up to the individual''s expectation III. The risk of rate of return on the investment matching up to the individual''s expectation IV. The risk of losing some or all of a person''s initial investment',
     ARRAY['I & III',
            'I & II',
            'III & IV',
            'II & IV']),
    ('VUL',
     'The duties of the trustee of unit trust do not include:',
     ARRAY['Managing the portfolio of investment and administering the buying and selling of shares in the unit trust itself',
            'Ensuring that the fund manager adhere to the provision of the trust deeds',
            'Acting generally to protect the unit-holders',
            'Holding the pool of money and assets in trust in behalf of the investors']),
    ('VUL',
     'Policy fee payable by variable life insurance policy owner is to cover ___________',
     ARRAY['The handling charges by professional investment managers',
            'The price of each unit bought under the variable life insurance policy',
            'The mortality costs of the variable life insurance policy',
            'The administrative expenses of setting up the variable life insurance policy']),
    ('VUL',
     'The selling price under a variable life insurance policy is:',
     ARRAY['The price at which units under the policy are bought back by the life insurance company',
            'The price at which units under the policy are offered for sale by the life company',
            'Also known as the bid price',
            'A fixed amount throughout the life of the policy']),
    ('VUL',
     'Diversification in investment involves ___________:',
     ARRAY['Putting all the funds under management into one category of investment',
            'Spreading the risk of investment by not putting the fund into several categories of investment',
            'Reducing the risks of investment by putting one fund under management into several categories of investment',
            'Reducing the risks of investment by putting all one''s eggs in one basket']),
    ('VUL',
     'Variable life funds can be invested in any financial instruments including cash funds, bond funds, equity funds, property funds, specialized funds, and diversified funds. Equity funds ___________:',
     ARRAY['Invest in shares of stocks and the magnitude of the change in unit prices will only depend on the quantity of the equities held',
            'Invest in shares of stocks and during market recession, such as assets are usually the last to depreciate',
            'Invest in shares of stocks which are inherently of lower risk in nature and the prices of stocks are stable',
            'Invest in shares of stocks and investors who buy such assets usually aim for capital appreciation']),
    ('VUL',
     'Which of the following statements describe the differences between variable life products and participating products? I. Variable life products allow policyholders to vary the premium payments unlike participating products. II. Variable life products can take the form of whole life or endowment policies with Participating products. III. Variable life products allow policyholders to pay future single premiums from time to time to add more units to his account unlike participating products.',
     ARRAY['I, II, and III',
            'I',
            'I and III',
            'II and III']),
    ('VUL',
     'Assuming no movement in the prices and charges / fees are deducted after the single premium has been invested into the account, how much will the policyholder lose if he surrenders the policy now? Bid price = Ps. 13.00; Bid-offer spread = 4%; Single premium = Ps. 450,000; Policy fee = Ps. 1,800; Admin and Mortality charge = 3%. Sum assured is 200% of single premium or the value of the units, whichever is higher.',
     ARRAY['Ps. 43,400.90',
            'Ps. 33,246.78',
            'Ps. 22,500.00',
            'Ps. 15,299.96']),
    ('VUL',
     'Which of the following statements BEST describes "variable life" policies?',
     ARRAY['It is a fixed premium policy with returns that will not vary with the underlying value of investments.',
            'It is a fixed premium policy with returns that will vary with the underlying value of investments.',
            'It is a flexible premium policy with returns that will not vary with the underlying value of investments.',
            'It is a flexible premium policy with returns that will vary with the underlying value of investments.']),
    ('VUL',
     'Which of the following factors contribute to the specific risk of an investment: I. Rate of corporate taxes II. Fraud by senior management III. Financial leverage of the company',
     ARRAY['I and II',
            'II and III',
            'I and III',
            'I, II and III']),
    ('VUL',
     'Investing in bonds offers the following advantages EXCEPT',
     ARRAY['It offers protection to the principal and guaranteed steady stream of income',
            'It is a place of temporary refuge when the investor foresees that the market outlook is uncertain',
            'It allows the investor a chance for capital preservation',
            'It enables the investor an opportunity for capital appreciation']),
    ('VUL',
     'Rank the following investment instruments in terms of their level of risks, from the least risky to the most risky. I. cash and deposit II. derivatives III. a well diversified investment portfolio of a company IV. stock options',
     ARRAY['I, IV, III & II',
            'I, III, IV & II',
            'I, IV, II, & III',
            'I, II, III & IV']),
    ('VUL',
     'In risk-return profile of cash funds, bond funds, balanced funds, managed funds and equity funds, a risk-return graph will show that ___________ I. Higher return normally comes with lower risk II. Higher return normally comes with higher risk III. At the top end of the graph are the equity funds IV. The relatively risk-less cash funds sit at the bottom end of the graph',
     ARRAY['I, II, & III',
            'II, III, & IV',
            'I, II & IV',
            'I, III, & IV']),
    ('VUL',
     'Which of the following statements are TRUE? I. The policy value of variable life policies is determined by the offer price at the time of valuation. II. The policy value of endowment policies is the cash value plus any accumulated dividends less any outstanding loans due at the time of surrender. III. The life company needs to maintain a separate account for variable life policies distinct from the general account.',
     ARRAY['I & II',
            'I, II, & III',
            'I & III',
            'II & III']),
    ('VUL',
     'Which of the following information is NOT required to be disclosed to policyholders of variable life policies?',
     ARRAY['The net withdrawal value as of the statement date.',
            'The premiums received and charges levied during the period',
            'The basis and frequency for valuing the assets.',
            'Number and value of units held at the beginning of the period; bought and sold during the period; and held at the end of the period.']),
    ('IIAP_A',
     'A single premium policy means a policy',
     ARRAY['requiring only a single premium each year',
            'under which only one premium payment is required',
            'only available to single individuals',
            'on which no more than one premium can be paid in advance']),
    ('IIAP_A',
     'A fixed amount added to the premium of a given policy regardless of policy size is known as',
     ARRAY['policy fee',
            'policy reserve',
            'policy values',
            'extra premium']),
    ('IIAP_A',
     'To be able to calculate the required premiums for a given policy, the agent must know the applicant''s',
     ARRAY['age',
            'choice of plan',
            'face amount desired',
            'all of the above']),
    ('IIAP_A',
     'To calculate premiums for the other modes of premium payment, the annual premium is',
     ARRAY['divided by the desired number of premium payments',
            'divided by a conversion factor for the mode of payment desired',
            'multiplied by a conversion factor for the mode of payment desired',
            'multiplied by a constant conversion factor']),
    ('IIAP_A',
     'A father enters into a life insurance contract on behalf of his child. In this case, the father is the',
     ARRAY['insured',
            'beneficiary',
            'insurer',
            'applicant-owner']),
    ('IIAP_A',
     'The convertible feature of a term insurance policy provides that the policy may be',
     ARRAY['changed to a permanent insurance policy without evidence of insurability',
            'changed to another life',
            'cashed for a guaranteed sum',
            'changed to permanent insurance with evidence of insurability']),
    ('IIAP_A',
     'Within two years of buying a life insurance policy, you are accidentally killed when your car hits a tree. In these circumstances the insurance company will',
     ARRAY['refund premium because it is suicide',
            'pay double the face amount',
            'pay the face amount',
            'pay nothing']),
    ('IIAP_A',
     'When explaining dividends, the following information must be supplied',
     ARRAY['that they are not guaranteed',
            'the dividends paid-up in the previous years',
            'the anticipated dividends',
            'the relation to the cost of the policy']),
    ('IIAP_A',
     'Part of the premium paid by a policyholder is invested by the insurance company. In premium computation, this factor is known as',
     ARRAY['interest',
            'investment',
            'loading',
            'mortality']),
    ('IIAP_A',
     'The parties involved in life insurance contract are the',
     ARRAY['insurance company and agent',
            'insurance company and insured',
            'agent and insured',
            'insured and beneficiary']),
    ('IIAP_A',
     'The fundamental advantage of the use of insurance as a means of meeting economic losses is that through insurance these losses are',
     ARRAY['spread over a large number of people',
            'deferred for a specified period of time',
            'reduced for the group as a whole through the multiplier effect',
            'met as they arise through savings accumulated on an assessment basis']),
    ('IIAP_A',
     'Life insurance contributes directly to the welfare and progress of the country by',
     ARRAY['accumulating capital for investment in commerce and industry',
            'partially relieving the community of the care of dependents',
            'encouraging provisions for the future',
            'all of the above']),
    ('IIAP_A',
     'The number of years that persons at a given age will live on the average as shown by the mortality table is called',
     ARRAY['law of large numbers',
            'life income option',
            'life annuity',
            'life expectancy']),
    ('IIAP_A',
     'An insurance plan which offers both protection and savings is called',
     ARRAY['Temporary Plan',
            'Permanent Plan',
            'Participating Plan',
            'Non-participating Plan']),
    ('IIAP_A',
     'A man with moderate means can have maximum protection possible through',
     ARRAY['20 Yr. Endowment',
            'Limited Pay Life',
            'Term Insurance',
            'Whole Life Insurance']),
    ('IIAP_A',
     'Mr. Juan Valdez wants a policy which will entitle him to receive dividends yearly. What will you recommend to Mr. Valdez?',
     ARRAY['Participating',
            'Non-participating Plans',
            'Term Insurance',
            'None of the above']),
    ('IIAP_A',
     'Which of the following can give the longest protection?',
     ARRAY['20 Yr. Endowment',
            'Endowment at 65',
            'Ordinary Life',
            '20 Yr. Term']),
    ('IIAP_A',
     'An Individual, at age 35, purchases a policy under which he will in 20 years receive the face amount of the policy himself if he is still alive at that date. This policy is obviously a',
     ARRAY['20 Yr. Endowment',
            '20 Pay Life',
            '20 Yr. Term',
            'None of the above']),
    ('IIAP_A',
     'In a 20 Life policy',
     ARRAY['protection is until age 100, payment of premium is for 20 years',
            'protection is until age 100, payment of premium until age 100',
            'protection is for 20 years, payment of premium is for 20 years',
            'protection is for 20 years, payment of premium until age 100']),
    ('IIAP_A',
     'A participating plan entitles the policyowner to receive a return of excess premium. Such is termed as:',
     ARRAY['endowment',
            'dividends',
            'cash value',
            'cash surrender value']),
    ('IIAP_A',
     'Mrs. Rose Cortez owns a policy which does not provide for the build up of cash values and whose premiums remain level. Mrs. Cortez owns:',
     ARRAY['Ordinary Life',
            'Limited Pay Life',
            'Decreasing Term',
            'Level Term']),
    ('IIAP_A',
     'Two attractive features of a Term insurance are:',
     ARRAY['convertibility and cash values',
            'cash values and dividends',
            'protection and dividends',
            'convertibility and renewability']),
    ('IIAP_A',
     'A term insurance which allows the policyowners to convert it to a permanent insurance within a specified period without evidence of insurability contains _____ features:',
     ARRAY['convertibility',
            'renewability',
            'dividend option',
            'both a & b']),
    ('IIAP_A',
     'A term policy only offers',
     ARRAY['cash values',
            'protection',
            'savings',
            'dividends']),
    ('IIAP_A',
     'The main difference between a term plan and a permanent plan is',
     ARRAY['permanent plans provide both protection and savings while term plans offer protection only',
            'permanent plans provides savings and dividends while term plans provide savings only',
            'permanent plans can be converted and renewed while term plans cannot',
            'all of the above']),
    ('IIAP_A',
     'The savings element of permanent plans allows for the build up of',
     ARRAY['dividends',
            'cash values',
            'maturity benefits',
            'death benefits']),
    ('IIAP_A',
     'A term rider is',
     ARRAY['a term policy with a waiver of premium',
            'another name for a convertible term policy',
            'a renewable term policy',
            'a term insurance added to a permanent plan']),
    ('IIAP_A',
     'An optional rider which can be attached to a policy stopping further premium payment in the event of disability is called',
     ARRAY['policyholder protection clause',
            'accidental death and dismemberment',
            'waiver of premium',
            'total disability monthly income']),
    ('IIAP_A',
     'For the waiver of premium to be effective',
     ARRAY['disability must be total',
            'disability must be permanent',
            'both a & b',
            'either a or b']),
    ('IIAP_A',
     'Disability benefits are not paid',
     ARRAY['for self-inflicted injuries',
            'if there is a loan against the policy',
            'if all the policy dividends have been withdrawn',
            'if disability resulted from sickness only']),
    ('IIAP_A',
     'Mr. Pedro Cruz became paralyzed as a result of jumping out of the window in an attempt to commit suicide. Under the usual provisions of a disability income policy, he would be entitled to',
     ARRAY['receive the total disability income benefit and the waiver of premiums',
            'receive partial disability benefits',
            'be granted the waiver of premium',
            'receive neither disability income nor waiver of premiums']),
    ('IIAP_A',
     'A person wanting a greater coverage for the least amount of premium has an option of attaching what rider in his permanent life policy?',
     ARRAY['a waiver of premium',
            'term insurance rider',
            'guaranteed insurability rider',
            'accidental death rider']),
    ('IIAP_A',
     'One supplementary benefit offered is a payor''s benefit which is intended to',
     ARRAY['provide for the return of premiums to an adult payor in the event that a minor insured dies',
            'provide a waiver of premium benefit in the event of death or disability of the person paying the premium',
            'allow the insurance company to pay the policy''s proceeds to the person who seems equitable entitled to the proceeds',
            'assure that the adult payor will retain a vested in the policy when the insured reaches the age of majority']),
    ('IIAP_A',
     'If an insured is disabled and his life insurance policy is being continued in force through the waiver of premium, the dividends of the policy would',
     ARRAY['cease',
            'continue at reduced rate',
            'continue as if the owner is paying the premium',
            'continue but they would be applied toward the premium being waived']),
    ('IIAP_A',
     'A policy with a minor as the proposed insured is called',
     ARRAY['rated policy',
            'juvenile policy',
            'regular policy',
            'substandard policy']),
    ('IIAP_A',
     'Life insurance policies for which higher than standard premium rates are payable are said to be',
     ARRAY['rated policies',
            'contingent policies',
            'non-participating policies',
            'conditional policies']),
    ('IIAP_A',
     'Since the purchase of life insurance is a voluntary choice, the individual must meet',
     ARRAY['comprehensive inspection report',
            'certain standards of health and occupation',
            'minimum income requirement',
            'all of the above']),
    ('IIAP_A',
     'Which of the following factors would have the least effect on the premium charged for life insurance',
     ARRAY['age',
            'occupation',
            'income',
            'all of the above']),
    ('IIAP_A',
     'Insurance Companies have various sources of information about the insured. These are',
     ARRAY['application form',
            'medical information bureau',
            'inspection report',
            'all of the above']),
    ('IIAP_A',
     'Anti-selection occurs',
     ARRAY['when an agent thinks only of his own interest and not of his policyowners',
            'when you purchase bad stocks with expectation that they will improve',
            'when the insurance company accepts more than its share of poor risks',
            'when persons in poor health wish to buy insurance']),
    ('IIAP_A',
     'In insurance, risk means',
     ARRAY['chances of you being declined by the company',
            'hazard on people''s lives',
            'chances of the beneficiary being paid',
            'none of the above']),
    ('IIAP_A',
     'In an application, the information that must be disclosed include',
     ARRAY['only his date and place of birth',
            'only his family history',
            'every fact in his knowledge that is material to the insurance',
            'only information he wants the agent to know']),
    ('IIAP_A',
     'In insurance risks are classified as',
     ARRAY['unacceptable and acceptable',
            'regular and irregular',
            'standard, substandard and declined',
            'complete and incomplete']),
    ('IIAP_A',
     'A risk is considered substandard based on any or all of the following criteria',
     ARRAY['death, occupation and moral character',
            'occupation, moral character and family health history',
            'income, educational attainment and occupation',
            'death, income and educational background']),
    ('IIAP_A',
     'A hazardous occupation could be defined as',
     ARRAY['an occupation the duties of which expose the insured to a degree of danger of sustaining injury',
            'an occupation in an unhealthy working condition exposing the insured to elements which can cause sickness',
            'an occupation which exposes the insured to social hazards',
            'all of the above']),
    ('IIAP_A',
     'Statements in the application forms are',
     ARRAY['guarantees',
            'representations',
            'warranties',
            'none of the above']),
    ('IIAP_A',
     'An agent is filling up the Agent''s Confidential Report. What information must he put in his report?',
     ARRAY['information about insured''s standing in the community',
            'information about insured''s finances',
            'all information he knows which are material to the application for insurance',
            'a & b only']),
    ('IIAP_A',
     'Mr. Roel Reyes has been confined in a hospital 3 years prior to his application for insurance. He, therefore, needs to give the following information',
     ARRAY['name of attending doctor, diagnosis, date of confinement',
            'the bill and medicines',
            'name of doctor only',
            'date of confinement only']),
    ('IIAP_A',
     'Insurance companies have a source of confidential medical information on applicants for life insurance. This is the',
     ARRAY['agents confidential report bureau',
            'inspection reports bureau',
            'financial standing bureau',
            'medical impairment bureau']),
    ('IIAP_A',
     'Insurance companies which are owned by the policyowners are examples of',
     ARRAY['stock companies',
            'mutual companies',
            'family corporation',
            'open-end companies']),
    ('IIAP_A',
     'Stock companies are owned by',
     ARRAY['policyowners',
            'stockholders',
            'creditors',
            'government']),
    ('IIAP_A',
     'Why is it important that the application is the basis of the policy?',
     ARRAY['because the completed application is the basis of the policy contract and the company may accept or reject an application based on the information given in the application',
            'for the agent to have available data of his prospect in connection with future sales',
            'to avoid the necessity of the insurer putting all relevant details in the contract',
            'none of the above']),
    ('IIAP_A',
     'Which one of the following statements is correct?',
     ARRAY['advertising by life insurance agents is prohibited',
            'all information about a client or a prospective client has to be treated as confidential',
            'the agents should always recommend the amount and type of policy to a prospective client which would be profitable for the company',
            'when an agent advertises his services in the press, he is not allowed to state the name of his company']),
    ('IIAP_A',
     'Choose the incorrect statement: The entire contract between the policyowner and the insurance company include:',
     ARRAY['the application and the policy',
            'any verbal statement made by the agent to the application',
            'any document attached to the policy when issued',
            'any subsequent written amendments to the contract']),
    ('IIAP_A',
     'Life insurance is',
     ARRAY['a luxury afforded by the rich',
            'only available to a specific group',
            'a cooperative risk-sharing plan',
            'a speculative risk']),
    ('IIAP_A',
     'A life insurance company earns income from two main sources',
     ARRAY['premium income and investment income',
            'mortgage income and premium income',
            'dividend income and interest income',
            'mortgage income and dividend income']),
    ('IIAP_A',
     'The official who makes the necessary assumption and calculation with respect to the principal elements of life insurance premium in order to arrive at the premium rates to be charged is the',
     ARRAY['life agent',
            'senior statistician',
            'Insurance Commissioner',
            'Actuary']),
    ('IIAP_A',
     'The term loading means',
     ARRAY['the difference between the gross and net premiums for the purpose of paying the insurance overhead expenses including commissions and taxes',
            'the amount which the company will lend to the policyholder with the policy as a security',
            'the amount payable in the event of the occurrence of a loss which renders him unfit for insurance',
            'None of the above']),
    ('IIAP_A',
     'Life insurance can provide money when income stops because of',
     ARRAY['disability',
            'death',
            'retirement',
            'all of the above']),
    ('IIAP_A',
     'The three elements that make up a life insurance premium are',
     ARRAY['mortality experience, investment earnings and operating expenses',
            'cash values, dividends and paid up values',
            'cash values, loan values and paid up values',
            'past dividend experience, present dividend and projected interest']),
    ('IIAP_B',
     'If the insured dies during the grace period of an unpaid life insurance policy, the amount payable to the beneficiary is usually the',
     ARRAY['total premium paid plus interest.',
            'cash surrender value of the policy minus the unpaid premium.',
            'face amount of the policy minus the unpaid premium.',
            'full face amount.']),
    ('IIAP_B',
     'Which of the following statements is correct?',
     ARRAY['an insurance agent''s license will be renewed when the Commissioner is satisfied that the information in the application is accurate and all requirements are met.',
            'an insurance agent''s license is valid only for one month.',
            'an insurance agent''s license is valid during the lifetime of the agent.',
            'an insurance agent''s license will be renewed when the corresponding application and fee are received by the Insurance Commissioner.']),
    ('IIAP_B',
     'The insurance industry is under government regulations because',
     ARRAY['it is required to account for money spent in company operations.',
            'it pays high taxes.',
            'it affects public interest.',
            'it is a charitable institution.']),
    ('IIAP_B',
     'Which of the following statements is correct?',
     ARRAY['an agent is allowed to share commissions when selling a whole life policy but not when selling a term policy.',
            'an agent is allowed to share commissions with another licensed agent or agents but with no one else.',
            'sharing the commission with any other person is called twisting.',
            'an agent is not allowed to share commissions with any person.']),
    ('IIAP_B',
     'Which of the following statements is correct?',
     ARRAY['rebating of premiums can only be authorized by the head office of the insurer.',
            'a life insurance is not allowed to identify on his letterhead the name of the insurer he represents.',
            'life insurance agents are allowed to act for two insurers at the same time under the same license.',
            'rebating of premiums by an insurance agent is prohibited.']),
    ('IIAP_B',
     'Persuading a policyowner, directly or indirectly, to surrender or lapse a policy in one company and replacing it with a policy from another company is',
     ARRAY['rebating',
            'twisting',
            'knocking',
            'discounting']),
    ('IIAP_B',
     'Interest is charged on policy loans',
     ARRAY['for registered policies only.',
            'if the loan is outstanding for more than a year. A loan repaid within a year is interest free.',
            'to replace investment income the insurer cannot earn since a loan has been granted.',
            'for participating policies only.']),
    ('IIAP_B',
     'Rebating is',
     ARRAY['dating the policy a month in advance.',
            'giving false information.',
            'twisting.',
            'premium discrimination against policyholders.']),
    ('IIAP_B',
     'An insurance agent''s license can be revoked for',
     ARRAY['fraudulent practices.',
            'violation of any provision of the Insurance code.',
            'misrepresentation in the application for license.',
            'any or all of the above.']),
    ('IIAP_B',
     'One example covered under the ethical practices and procedures is',
     ARRAY['keep all policyholders information confidential.',
            'always recommend a will.',
            'never drink in front of clients.',
            'always pick up the first premium with the application for insurance.']),
    ('IIAP_B',
     'The term knocking means',
     ARRAY['promising to pay to two annuitants a fixed annual income as long as both survive.',
            'making derogatory remarks about competing underwriters or companies.',
            'the number of years that person at a given age will live on the average as shown by the mortality table.',
            'None of the above']),
    ('IIAP_B',
     'The following are unethical practices in the solicitation and procurement of insurance except',
     ARRAY['misleading estimates of the dividends or shares of surplus to be received thereon.',
            'inducing a policyholder to lapse, forfeit or surrender a policy he holds for another company.',
            'misrepresenting the terms of any policy issued by any insurance company or the benefits or advantages promised thereon.',
            'obtaining or attempting to obtain a license by fraud or misrepresentation.']),
    ('IIAP_B',
     'Twisting is',
     ARRAY['paying the premium on one policy by surrendering the dividends of another policy.',
            'the replacement of a policy in one company with another policy in another company.',
            'an attempt made by an insurance to secure the services of an agent from another company.',
            'an offense which does not apply to variable concepts.']),
    ('IIAP_B',
     'The misstatement of facts by either of the parties of insurance, whether in writing or orally, preliminary and in reference to making the insurance contract is',
     ARRAY['knocking',
            'overloading',
            'misrepresentation',
            'twisting']),
    ('IIAP_B',
     'Selling a person more insurance than what is warranted by his sources is called',
     ARRAY['overloading',
            'twisting',
            'rebating',
            'knocking']),
    ('IIAP_B',
     'An agent is prohibited from doing all of the following except:',
     ARRAY['alter an application without the applicant''s prior written approval.',
            'convince a prospective client to cancel his policy in one insurance company in order to buy a policy in the insurance company represented by the agent.',
            'refund some of his commission to his client.',
            'make complete comparisons of policies he sells and those offered by competing insurance companies.']),
    ('IIAP_B',
     'Inducing an insured to lapse or forfeit his insurance',
     ARRAY['is not allowed by the conditions of the contract.',
            'is always to the advantage of the policyholder.',
            'is an offense in the great majority of cases.',
            'is a matter left entirely to the discretion of the agent.']),
    ('IIAP_B',
     'The suicide clause is in effect for',
     ARRAY['the first 6 months.',
            'the first year.',
            'the first 2 years.',
            'the first 18 months.']),
    ('IIAP_B',
     'The three non-forfeiture values in a permanent policy are',
     ARRAY['cash dividends, bonus additions and extended term insurance.',
            'cash surrender values, loan value, assignment.',
            'waiver of premium, reinstatement and the policy loan.',
            'cash surrender value, paid value, extended term insurance.']),
    ('IIAP_B',
     'What are the basic settlement options?',
     ARRAY['cash surrender value, automatic premium loan.',
            'fixed amount, fixed period, interest, fixed period and for life.',
            'double indemnity, total disability waiver of premium.',
            'policy loans, assignment, beneficiary designation.']),
    ('IIAP_B',
     'In case of misstatement of age',
     ARRAY['the policy is cancelled and a new one is issued for the correct age.',
            'the insured can be changed.',
            'the amount of insurance is adjusted to the amount which the premium paid at the correct age would have purchased.',
            'the policy remains in force and the company cannot contest it.']),
    ('IIAP_B',
     'Which of the following is a settlement option?',
     ARRAY['policy loan',
            'cash surrender value',
            'extended term insurance option',
            'interest on insurance proceeds']),
    ('IIAP_B',
     'Name the provision in a permanent life insurance policy under which, if the premiums are discontinued, full insurance coverage will be maintained for a specified period.',
     ARRAY['extended term insurance',
            'paid up insurance',
            'paid up additions',
            'life income option']),
    ('IIAP_B',
     'Which one of the following is not derived from the non-forfeiture values?',
     ARRAY['cash surrender value',
            'paid up insurance',
            'dividends',
            'extended term insurance']),
    ('IIAP_B',
     'Mr. Dela Cruz stated in his application that he was 30 years of age and a policy was issued to him on that basis. When he died twenty years later it was found out that, in fact, he was 34 years of age at the time of his application. In conformity with the Insurance Code, the company',
     ARRAY['paid the amount of insurance payable to his beneficiary reduced in relation to his actual age at the time the contract was signed.',
            'paid one half of the face value of the policy.',
            'need not pay the face value of the policy, but refund all premiums paid.',
            'paid the full face value of the policy without any extra charges.']),
    ('IIAP_B',
     'In the event that the policyowner elects the paid-up insurance option',
     ARRAY['premiums stop and the policy continues for a full face until age 65.',
            'premiums cease and protection continues for a reduced amount.',
            'insurance continues at a reduced amount and with reduced premium.',
            'the policy will automatically terminate.']),
    ('IIAP_B',
     'If a policyowner commits suicide within one year, what''s the company''s liability?',
     ARRAY['the company is not liable at all.',
            'the company would be liable for the payment of the face value of the policy.',
            'the company would be liable for the payment of the premiums paid by the insured only.',
            'none of the above']),
    ('IIAP_B',
     'Which of the non-forfeiture option gives the largest amount of protection?',
     ARRAY['fully paid insurance',
            'cash surrender value',
            'extended term insurance',
            'all of the above give equal protection']),
    ('IIAP_B',
     'Any policy which has lapsed can be reinstated subject to normal conditions of proof of insurability within',
     ARRAY['three years',
            'six months',
            'one year',
            'two years']),
    ('IIAP_B',
     'Benefits payable under health insurance policies cover',
     ARRAY['accidental death and dismemberment benefits.',
            'expense reimbursement benefits.',
            'disability income benefits.',
            'all of the above']),
    ('IIAP_B',
     'With employer-employee groups, an employee does not fill out a personal application for insurance. Instead he merely fills out.',
     ARRAY['an enrollment card.',
            'a registration card.',
            'a certificate of insurance coverage.',
            'a salary deduction form.']),
    ('IIAP_B',
     'In the event an employee leaves the company in which he is a member of its group insurance policy, his group coverage can be changed to an individual policy using the',
     ARRAY['policy exchange facility.',
            'conversion privilege.',
            'change of plan provision.',
            'policy change form.']),
    ('IIAP_B',
     'For a contract to be legal and binding',
     ARRAY['parties to the contract must be members of the bar.',
            'parties to the contract must be legally competent.',
            'parties to the contract must be above 21.',
            'parties to the contract must possess blood relationship.']),
    ('IIAP_B',
     'The insurance code specifies that a contract does not take effect unless',
     ARRAY['the policy is delivered to an insured, his assignee or agent, or to a beneficiary.',
            'payment of the first premium is made to the insurer or its authorized agent.',
            'no change has taken place in the insurability of the life to be insured between the time the application was completed and the time the policy was delivered.',
            'the insured has named in the policy no fewer than two beneficiaries.']),
    ('IIAP_B',
     'All of the following would be practicable to become beneficiaries except',
     ARRAY['children by former marriage.',
            'brothers and sisters.',
            'someone who owes you money.',
            'someone to whom you owe money.']),
    ('IIAP_B',
     'Under the law pertaining to life insurance',
     ARRAY['only minor children can be named irrevocable beneficiaries.',
            'only the wife can be named irrevocable beneficiary.',
            'only the wife and the children can be named irrevocable beneficiaries.',
            'any person with insurable interest can be named irrevocable beneficiary.']),
    ('IIAP_B',
     'When the proceeds of a life insurance policy are left with the company to earn interest',
     ARRAY['income tax is levied on the proceeds.',
            'income tax is levied on the interest earnings of the proceeds.',
            'estate tax is levied on the proceeds.',
            'donor''s tax is levied on the proceeds.']),
    ('IIAP_B',
     'A person has insurable interest on the life of',
     ARRAY['his child or grandchild.',
            'any person upon whom he is wholly or in part dependent on, or from whom he is receiving support or education.',
            'any person in whom he has pecuniary interest.',
            'all of the above']),
    ('IIAP_B',
     'Anybody can be designated a beneficiary except',
     ARRAY['a creditor.',
            'minors.',
            'those expressly prohibited by law to receive donations.',
            'all of the above']),
    ('IIAP_B',
     'The common practice of most life insurers is that the life insurance goes into force',
     ARRAY['when the application is received by the branch office.',
            'when the policy is delivered to the applicant.',
            'in accordance with the legal stipulation of the Insurance Code.',
            'when the agent gives a binding receipt.']),
    ('IIAP_B',
     'According to insurance law, a common-law spouse cannot be designated a beneficiary',
     ARRAY['since there is no benefit of marriage in the relationship.',
            'if his/her legal partner is still living and the previous marriage has not been legally dissolved.',
            'since the common-law relationship is an immoral relationship.',
            'all of the above']),
    ('IIAP_B',
     'Policy reserves are future obligations on the part of',
     ARRAY['the Insurance Commission.',
            'the Insurance Company.',
            'the beneficiary.',
            'the policyowner.']),
    ('IIAP_B',
     'Which one of the following provisions in a permanent life insurance policy may lapse for non-payment of premium?',
     ARRAY['Guaranteed Insurability',
            'Automatic Premium Loan',
            'Settlement Options',
            'Reinstatement Provision']),
    ('IIAP_B',
     'A policyholder may obtain money from the insurance company and still remain insured by',
     ARRAY['surrendering the policy for its cash value.',
            'discontinuing payment of premium for some period.',
            'taking a policy loan.',
            'taking the extended insurance option.']),
    ('IIAP_B',
     'When you bought an insurance policy on your wife''s life you were 27 and she was 26, but you stated that you were 26 and she was 27. Five years later your wife died. The insurance company will pay',
     ARRAY['the face amount.',
            'the face amount adjusted for misstatement of age.',
            'the sum of the premium paid.',
            'slightly less than the face amount.']),
    ('IIAP_B',
     'If the policy did not contain the name of a beneficiary, the beneficiary will be',
     ARRAY['the wife.',
            'the children',
            'the insured''s brothers and sisters.',
            'the insured''s estate.']),
    ('IIAP_B',
     'If a policyowner whose wife is the irrevocable beneficiary wishes to cash in his policy, he must',
     ARRAY['tell his wife what he is going to do.',
            'first take a loan on the policy.',
            'have the check issued in the name of his wife.',
            'have the wife''s consent.']),
    ('IIAP_B',
     'If a policy with the accidental death rider becomes paid up',
     ARRAY['the accidental death rider ceases.',
            'the face amount of the policy is reduced.',
            'premiums on the basic policy stop but the rider premium continues.',
            'none of the above']),
    ('IIAP_B',
     'An annuity plan',
     ARRAY['offers life insurance protection.',
            'offers the waiver of premium benefit.',
            'is the same as an endowment plan.',
            'is a purchase of income.']),
    ('IIAP_B',
     'The person who purchases the annuity plan is called the',
     ARRAY['assignor.',
            'owner.',
            'insured.',
            'annuitant.']),
    ('IIAP_B',
     'All of the following statements regarding a life insurance application are correct except',
     ARRAY['it must be signed by the applicant.',
            'usually it will be a part of the policy contract.',
            'misstatement of material facts could void the policy during the contestable period.',
            'statements made on the applications are warranties.']),
    ('IIAP_B',
     'Prior to granting a license, the IC requires proof of',
     ARRAY['a clean record of employment.',
            'a reasonable educational background.',
            'a prospective agent''s character and reputation.',
            'all of the above']),
    ('IIAP_B',
     'The IC has the power to adjudicate insurance claims against insurance companies for any single claim not exceeding',
     ARRAY['P 1,000,000.00',
            'P 250,000.00',
            'P 100,000.00',
            'P 5,000,000.00']),
    ('IIAP_B',
     'For life insurance coverage to be valid, insurable interest must exist',
     ARRAY['only at the inception of the policy.',
            'only at the time of the loan.',
            'throughout the entire lifetime of the policy.',
            'both at the time of the policy issue and at the time of the loan but not necessarily throughout the lifetime of the policy.']),
    ('IIAP_B',
     'In the case of life insurance, a sale is considered completed if the application is signed and payment of the first premium is made by the applicant. For the sale to be considered completed',
     ARRAY['a medical examination has to be made first.',
            'payment of the first premium has to be made by the applicant in full or in part, as specified. One of the acceptable methods of settlement is by cash or check in part, with a note for the balance.',
            'payment of the first premium has to be made in full by a note first.',
            'the first premium has to be paid for in full and in cash.']),
    ('IIAP_B',
     'An automatic premium loan differs from the other policy loans in that an automatic premium loan',
     ARRAY['need not be repaid by the policyowner.',
            'must be repaid during the policy year in which it is granted.',
            'goes into effect requiring no separate action from the policyowner.',
            'involves higher interest payments because of the greater cost of administration.']),
    ('IIAP_B',
     'The typical grace period provision in a life insurance policy obliges the life insurance company to',
     ARRAY['establish a policy loan to cover any premium which the policyowner fails to pay by due date.',
            'keep the policy in force for the duration of any major disability suffered by the policyowner.',
            'allow the policyowner a three-month extension beyond the due date to make the late premium payment without penalty.',
            'none of the above']),
    ('IIAP_B',
     'When a policy is assigned absolutely',
     ARRAY['the assignee acquires all the rights and interests of the original policyholder.',
            'the original policyholder still can exercise some of the rights.',
            'the original beneficiary is not changed.',
            'none of the above']),
    ('IIAP_B',
     'If policyowner does not pay a premium on the due date, the policy will immediately',
     ARRAY['lapse.',
            'be converted to a paid-up policy for a lesser amount.',
            'go into automatic premium loan.',
            'continue in full force for a period of grace.']),
    ('IIAP_B',
     'If a loan is taken on a participating policy, dividends for that policy while there is a loan against the policy will be',
     ARRAY['suspended.',
            'paid a reduced rate.',
            'Unaffected.',
            'Increased.']);

UPDATE choices c
   SET sort_order = array_position(o.texts, c.text)
  FROM questions q
       JOIN choice_order o
         ON o.exam_type = q.exam_type
        AND o.qtext = q.text
        AND NOT EXISTS (
                SELECT 1
                  FROM choices other
                 WHERE other.question_id = q.id
                   AND NOT (other.text = ANY (o.texts))
            )
 WHERE c.question_id = q.id;

UPDATE memorization_choices mc
   SET sort_order = array_position(o.texts, mc.text)
  FROM memorization m
       JOIN choice_order o
         ON o.exam_type = m.exam_type
        AND o.qtext = m.text
        AND NOT EXISTS (
                SELECT 1
                  FROM memorization_choices other
                 WHERE other.memorization_id = m.id
                   AND NOT (other.text = ANY (o.texts))
            )
 WHERE mc.memorization_id = m.id;

-- Anything the seed could not account for still needs a fixed order, or it
-- would keep shuffling. Alphabetical is arbitrary but it is the same every
-- time, which is the property that was missing.
UPDATE choices c
   SET sort_order = ranked.rn
  FROM (
        SELECT id,
               row_number() OVER (PARTITION BY question_id ORDER BY text) AS rn
          FROM choices
         WHERE sort_order IS NULL
       ) ranked
 WHERE c.id = ranked.id;

UPDATE memorization_choices mc
   SET sort_order = ranked.rn
  FROM (
        SELECT id,
               row_number() OVER (PARTITION BY memorization_id ORDER BY text) AS rn
          FROM memorization_choices
         WHERE sort_order IS NULL
       ) ranked
 WHERE mc.id = ranked.id;

ALTER TABLE choices ALTER COLUMN sort_order SET NOT NULL;
ALTER TABLE memorization_choices ALTER COLUMN sort_order SET NOT NULL;

COMMIT;

-- Every question should now have its options numbered 1..n with no repeats.
-- Both counts are expected to come back zero.
SELECT (
        SELECT COUNT(*)
          FROM (
                SELECT question_id
                  FROM choices
                 GROUP BY question_id
                HAVING COUNT(DISTINCT sort_order) <> COUNT(*)
               ) x
       ) AS questions_with_clashing_order,
       (
        SELECT COUNT(*)
          FROM (
                SELECT memorization_id
                  FROM memorization_choices
                 GROUP BY memorization_id
                HAVING COUNT(DISTINCT sort_order) <> COUNT(*)
               ) y
       ) AS memorization_with_clashing_order;
